name: 'safaricom_analytics'
version: '1.0.0'
config-version: 2
profile: 'saf_profile'

model-paths: ["models"]
test-paths: ["tests"]

models:
  safaricom_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
