name: 'equity_kenya_transactions'
version: '1.0.0'
config-version: 2
profile: 'equity_kenya'
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  equity_kenya_transactions:
    staging:
      +materialized: view
    marts:
      +materialized: table
