name: 'pan_africa_platform'
version: '1.0.0'
config-version: 2

profile: 'pan_africa_platform'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

seeds:
  pan_africa_platform:
    customer_master:
      +column_types:
        customer_id: varchar(50)
        account_number: varchar(50)
        phone_number: varchar(50)
        branch_code: varchar(50)

models:
  pan_africa_platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
