pan_africa_platform:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: equity_admin
      password: equity_password
      port: 5432
      dbname: pan_africa_platform
      schema: public
      threads: 4
  target: dev
