name: 'customs_trade'
version: '1.0.0'
config-version: 2

profile: 'customs_trade' # Reuse the same profile for the same DB

model-paths: ["models"]
seed-paths: ["../seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  customs_trade:
    staging:
      +materialized: view
    marts:
      +materialized: table
