"""
Fraud Detection Engine - Velocity Check Rules

Detects suspicious transaction patterns based on frequency, volume,
and timing patterns that deviate from customer baseline behavior.
"""

import logging
from typing import Dict, List, Tuple, Optional
from datetime import datetime, timedelta
from collections import defaultdict
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class Transaction:
    """Transaction record for fraud analysis."""
    transaction_id: str
    phone_number: str
    amount: float
    timestamp: datetime
    merchant_id: str
    location_code: str


@dataclass
class VelocityAlert:
    """Fraud alert generated by velocity checker."""
    alert_id: str
    phone_number: str
    alert_type: str
    risk_score: float
    description: str
    transactions: List[Transaction]
    generated_at: datetime


class VelocityChecker:
    """
    Detect high-frequency transaction patterns indicating potential fraud.
    
    Rules:
    - Multiple transactions within short time window
    - Transactions from different geographic locations
    - Unusual transaction frequency for customer
    """
    
    def __init__(
        self,
        time_window_minutes: int = 30,
        transaction_threshold: int = 5
    ):
        """
        Initialize velocity checker.
        
        Args:
            time_window_minutes: Time window for velocity check
            transaction_threshold: Number of transactions triggering alert
        """
        self.time_window_minutes = time_window_minutes
        self.transaction_threshold = transaction_threshold
        self.customer_baselines: Dict[str, Dict] = {}
    
    def check_transaction_velocity(
        self,
        transaction: Transaction,
        recent_transactions: List[Transaction]
    ) -> Optional[VelocityAlert]:
        """
        Check if transaction matches high-velocity fraud pattern.
        
        Args:
            transaction: Current transaction
            recent_transactions: Recent transactions from same customer
            
        Returns:
            VelocityAlert if suspicious, None otherwise
        """
        phone = transaction.phone_number
        alert_id = f"VEL_{transaction.transaction_id}"
        
        # Filter transactions within time window
        cutoff_time = transaction.timestamp - timedelta(
            minutes=self.time_window_minutes
        )
        
        window_transactions = [
            t for t in recent_transactions
            if t.phone_number == phone
            and t.timestamp >= cutoff_time
            and t.timestamp <= transaction.timestamp
        ]
        
        # Count transactions in window
        transaction_count = len(window_transactions) + 1  # Include current
        
        logger.info(
            f"Velocity check for {phone}: {transaction_count} transactions "
            f"in {self.time_window_minutes} minutes"
        )
        
        # Check against threshold
        if transaction_count >= self.transaction_threshold:
            risk_score = min(100, (transaction_count / self.transaction_threshold) * 50)
            
            alert = VelocityAlert(
                alert_id=alert_id,
                phone_number=phone,
                alert_type="HIGH_VELOCITY",
                risk_score=risk_score,
                description=(
                    f"High transaction velocity: {transaction_count} transactions "
                    f"in {self.time_window_minutes} minutes"
                ),
                transactions=window_transactions + [transaction],
                generated_at=datetime.now()
            )
            
            logger.warning(
                f"🚨 Velocity alert generated: {alert_id}, Risk: {risk_score}"
            )
            
            return alert
        
        return None
    
    def get_customer_baseline(
        self,
        phone_number: str,
        transactions: List[Transaction],
        days: int = 90
    ) -> Dict:
        """
        Calculate baseline velocity metrics for customer.
        
        Args:
            phone_number: Customer phone number
            transactions: Historical transactions
            days: Historical period in days
            
        Returns:
            dict: Baseline metrics
        """
        cutoff_date = datetime.now() - timedelta(days=days)
        
        customer_txns = [
            t for t in transactions
            if t.phone_number == phone_number
            and t.timestamp >= cutoff_date
        ]
        
        if not customer_txns:
            return {
                "transaction_count": 0,
                "avg_daily_transactions": 0,
                "avg_transaction_amount": 0,
                "max_transactions_per_hour": 0
            }
        
        # Calculate hourly transaction patterns
        hourly_counts = defaultdict(int)
        for txn in customer_txns:
            hour_key = f"{txn.timestamp.hour:02d}:00"
            hourly_counts[hour_key] += 1
        
        baseline = {
            "transaction_count": len(customer_txns),
            "avg_daily_transactions": len(customer_txns) / days,
            "avg_transaction_amount": sum(t.amount for t in customer_txns) / len(customer_txns),
            "max_transactions_per_hour": max(hourly_counts.values()) if hourly_counts else 0,
            "peak_hours": sorted(
                hourly_counts.items(),
                key=lambda x: x[1],
                reverse=True
            )[:5]
        }
        
        logger.info(
            f"Baseline for {phone_number}: "
            f"{baseline['avg_daily_transactions']:.2f} transactions/day"
        )
        
        return baseline
    
    def check_baseline_deviation(
        self,
        phone_number: str,
        transaction: Transaction,
        baseline: Dict,
        deviation_threshold: float = 2.0
    ) -> Optional[VelocityAlert]:
        """
        Check if transaction deviates significantly from customer baseline.
        
        Args:
            phone_number: Customer phone
            transaction: Transaction to check
            baseline: Customer baseline metrics
            deviation_threshold: Std deviations from normal
            
        Returns:
            VelocityAlert if deviation is significant
        """
        if baseline["avg_daily_transactions"] == 0:
            return None  # No baseline available
        
        # Calculate z-score
        expected_daily = baseline["avg_daily_transactions"]
        z_score = abs(1 - (expected_daily / (expected_daily + 1))) * 10
        
        if z_score > deviation_threshold:
            alert = VelocityAlert(
                alert_id=f"DEV_{transaction.transaction_id}",
                phone_number=phone_number,
                alert_type="BASELINE_DEVIATION",
                risk_score=min(100, z_score * 10),
                description=(
                    f"Transaction pattern deviates {z_score:.2f}σ "
                    f"from baseline ({expected_daily:.1f} daily avg)"
                ),
                transactions=[transaction],
                generated_at=datetime.now()
            )
            
            logger.warning(f"Baseline deviation alert: {alert.alert_id}")
            return alert
        
        return None


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    
    checker = VelocityChecker()
    print("Velocity checker module loaded")
