equity_kenya:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: equity_admin
      password: equity_password
      port: 5441
      dbname: equity_warehouse
      schema: public
      threads: 4
  target: dev
