version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: equity_admin
      POSTGRES_PASSWORD: equity_password
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_equity_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  airflow:
    image: apache/airflow:2.7.1
    command: standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://equity_admin:equity_password@postgres/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_DEPENDENCIES=dbt-postgres pandas requests psycopg2-binary sqlalchemy python-dotenv matplotlib
    volumes:
      - ./Equitel_EazzyPay_Analytics/dags:/opt/airflow/dags/equitel
      - ./Pan_Africa_Financial_Platform/dags:/opt/airflow/dags/pan_africa
      - ./Equitel_EazzyPay_Analytics:/opt/airflow/projects/equitel
      - ./Pan_Africa_Financial_Platform:/opt/airflow/projects/pan_africa
    depends_on:
      - postgres
    ports:
      - "8082:8080"

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    depends_on:
      - postgres

volumes:
  postgres_equity_data:
