kra_revenue:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres-kra') }}"
      user: kra_admin
      password: kra_password
      port: 5432
      dbname: kra_warehouse
      schema: public
      threads: 4
