name: 'equitel_analytics'
version: '1.0.0'
config-version: 2

profile: 'equitel_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  equitel_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
